apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: catalog-service
  selector:
    app: catalog-service
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: robjahn/keptn-orders-catalog-service:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: catalog-service
        env:
        - name: DT_TAGS
          value: "application=orders service=catalog-service"  
