apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: order-service
  selector:
    app: order-service
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: robjahn/keptn-orders-order-service:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: order-service
        env:
        - name: DT_TAGS
          value: "application=orders service=order-service"  
